import { Link, useRoute } from 'wouter';
import { useDrafts, type Draft } from '../lib/drafts';
import { ProjectHeader } from '../components/ProjectHeader';

type Column = {
  key: Draft['status'];
  label: string;
  pillClass: string;
  helper: string;
};

const COLUMNS: Column[] = [
  { key: 'pending', label: 'PENDING_REVIEW', pillClass: 'status-pill-amber', helper: 'Generated by the runtime pipeline, waiting for your call' },
  { key: 'approved', label: 'APPROVED', pillClass: 'status-pill-cyan', helper: 'Ready to publish. Mark posted with the URL once live' },
  { key: 'posted', label: 'POSTED', pillClass: 'status-pill-emerald', helper: 'Out in the world. Engagement comes back via Analyst' },
  { key: 'rejected', label: 'REJECTED', pillClass: 'status-pill-red', helper: 'Dropped. Kept for audit / learning' },
];

export function DraftsPage() {
  const [, params] = useRoute('/projects/:id/drafts');
  const projectId = params?.id;
  const drafts = useDrafts(projectId, 'all');

  if (!projectId) return null;

  const grouped: Record<Draft['status'], Draft[]> = {
    pending: [], approved: [], posted: [], rejected: [],
  };
  (drafts.data ?? []).forEach((d) => {
    grouped[d.status].push(d);
  });

  return (
    <div className="min-h-full">
      <ProjectHeader projectId={projectId} page="REVIEW" />
      <main className="max-w-[1400px] mx-auto px-6 py-6">
        <header className="mb-4 flex items-baseline justify-between gap-3 flex-wrap">
          <div>
            <h1 className="font-display text-2xl font-bold tracking-tight">Pipeline Queue</h1>
            <p className="font-mono text-[10px] uppercase tracking-wider text-muted mt-1">
              {drafts.data?.length ?? 0} drafts · live state via SSE
            </p>
          </div>
        </header>

        {drafts.isLoading && (
          <p className="font-mono text-xs uppercase tracking-wider text-muted">[LOADING] // drafts</p>
        )}

        {drafts.data && drafts.data.length === 0 && (
          <div className="rounded-lg border border-dashed border-border-color p-10 text-center max-w-md mx-auto">
            <p className="font-mono text-xs uppercase tracking-wider text-muted mb-4">
              [EMPTY] // No drafts yet
            </p>
            <p className="text-sm text-muted">
              Hit <span className="font-mono text-accent-cyan">[GENERATE_POST]</span> in the header to fire the
              runtime pipeline. A draft will appear here within ~10 seconds.
            </p>
          </div>
        )}

        {drafts.data && drafts.data.length > 0 && (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-3">
            {COLUMNS.map((col) => (
              <KanbanColumn
                key={col.key}
                column={col}
                drafts={grouped[col.key]}
                projectId={projectId}
              />
            ))}
          </div>
        )}
      </main>
    </div>
  );
}

function KanbanColumn({
  column,
  drafts,
  projectId,
}: {
  column: Column;
  drafts: Draft[];
  projectId: string;
}) {
  return (
    <section className="flex flex-col min-w-0">
      <header className="mb-3 flex items-baseline justify-between gap-2">
        <p className="font-mono text-[11px] uppercase tracking-wider text-text-primary">
          [{column.label}]
        </p>
        <span className="font-mono text-[10px] text-muted">{drafts.length}</span>
      </header>
      <div className="space-y-2 min-h-[100px]">
        {drafts.length === 0 && (
          <p className="font-mono text-[10px] uppercase tracking-wider text-muted/60 italic p-2">
            // empty
          </p>
        )}
        {drafts.map((d) => (
          <DraftCard key={d.id} draft={d} projectId={projectId} column={column} />
        ))}
      </div>
    </section>
  );
}

function DraftCard({ draft, projectId, column }: { draft: Draft; projectId: string; column: Column }) {
  const empathy = draft.empathyVerdict;
  const safety = draft.safetyVerdict;

  return (
    <Link
      href={`/projects/${projectId}/drafts/${draft.id}`}
      className="block rounded-lg border border-border-color bg-surface p-3 hover:border-accent-cyan/60 transition-colors group"
    >
      <header className="flex items-start justify-between gap-2 mb-2">
        <p className="font-mono text-[10px] uppercase tracking-wider text-muted">
          DRF_{draft.id.slice(0, 6)}
        </p>
        <span className={`status-pill ${column.pillClass}`}>{column.label.replace('_', ' ')}</span>
      </header>

      <p className="text-sm text-text-primary leading-snug line-clamp-2 mb-2">
        {draft.topicTitle}
      </p>

      <p className="font-mono text-[10px] uppercase tracking-wider text-muted mb-2">
        {draft.format.replace('_', ' ')}
        {draft.angle && (
          <>
            {' '}<span className="opacity-50">·</span>{' '}
            <span className="text-muted">{draft.angle.slice(0, 50)}{draft.angle.length > 50 ? '…' : ''}</span>
          </>
        )}
      </p>

      {(empathy || safety) && (
        <div className="flex flex-wrap gap-1 mb-2">
          {empathy && (
            <span
              className={`status-pill ${
                empathy === 'helpful'
                  ? 'status-pill-emerald'
                  : empathy === 'performative'
                    ? 'status-pill-amber'
                    : 'status-pill-red'
              }`}
            >
              {empathy.replace('_', ' ')}
            </span>
          )}
          {safety && (
            <span className={`status-pill ${safety === 'pass' ? 'status-pill-emerald' : 'status-pill-red'}`}>
              SAFETY: {safety}
            </span>
          )}
        </div>
      )}

      <p className="font-mono text-[10px] text-muted/70">
        {new Date(draft.createdAt).toLocaleString()}
      </p>
    </Link>
  );
}
